# Creation of arrary using Numpy

In [1]:
#Exp no:05

In [2]:
#Aim: Creation of arrary using Numpy

In [1]:
#Name : Vaishnavi Purushottam Raut
#Roll no. 40
#Section : 3B
#Date : 02/08/2024

In [3]:
import numpy as np

In [4]:
x=np.array([10,30,50,70,90])

In [5]:
x

array([10, 30, 50, 70, 90])

In [6]:
x2=np.array([[10,30,50,70,90],[20,40,60,80,100]])

In [7]:
x2

array([[ 10,  30,  50,  70,  90],
       [ 20,  40,  60,  80, 100]])

In [8]:
x3=np.array([[10,30,50,70,90],[20,40,60,80,100],[15,25,35,45,55]])

In [9]:
x3

array([[ 10,  30,  50,  70,  90],
       [ 20,  40,  60,  80, 100],
       [ 15,  25,  35,  45,  55]])